const REDUCERS_CONSTANTS = {
    FETCH: 'FETCH_POSTS',
    CREATE: 'CREATE_POST',
    UPDATE: 'UPDATE_POST',
    LIKE: 'LIKE_POST',
    DELETE: 'DELETE_POST',
    AUTH: 'AUTHENTICATE',
    LOGOUT: 'LOGOUT'
}

export default REDUCERS_CONSTANTS